
////////////////////////////////////////
//                                    //
//   Generated by CEO's YAAAG - V1.2  //
// (Yet Another Arya Addon Generator) //
//                                    //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class EasterBasketLargeGiftAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18060, 1, 0, 2}, {18060, 1, 1, 4}, {18060, 0, 0, 4}// 26	27	28	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new EasterBasketLargeGiftAddonDeed();
			}
		}

		[ Constructable ]
		public EasterBasketLargeGiftAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 11194, 0, -1, 0, 1033, -1, "Easter Basket", 1);// 1
			AddComplexComponent( (BaseAddon) this, 11194, 1, -1, 0, 1033, -1, "Easter Basket", 1);// 2
			AddComplexComponent( (BaseAddon) this, 11184, -1, -1, 0, 1033, -1, "Easter Basket", 1);// 3
			AddComplexComponent( (BaseAddon) this, 16830, 1, -1, 1, 1167, -1, "Easter Egg", 1);// 4
			AddComplexComponent( (BaseAddon) this, 16830, -1, -1, 1, 1165, -1, "Easter Egg", 1);// 5
			AddComplexComponent( (BaseAddon) this, 11181, 1, 1, 0, 1033, -1, "Easter Basket", 1);// 6
			AddComplexComponent( (BaseAddon) this, 11193, 1, 0, 0, 1032, -1, "Easter Basket", 1);// 7
			AddComplexComponent( (BaseAddon) this, 11194, 0, 1, 0, 1033, -1, "Easter Basket", 1);// 8
			AddComplexComponent( (BaseAddon) this, 11193, -1, 1, 0, 1033, -1, "Easter Basket", 1);// 9
			AddComplexComponent( (BaseAddon) this, 11193, -1, 0, 0, 1033, -1, "Easter Basket", 1);// 10
			AddComplexComponent( (BaseAddon) this, 9269, 0, 0, 0, 1037, -1, "Easter Basket", 1);// 11
			AddComplexComponent( (BaseAddon) this, 9269, 0, 1, 0, 1037, -1, "Easter Basket", 1);// 12
			AddComplexComponent( (BaseAddon) this, 9269, 1, 0, 0, 1037, -1, "Easter Basket", 1);// 13
			AddComplexComponent( (BaseAddon) this, 9269, 1, 1, 0, 1037, -1, "Easter Basket", 1);// 14
			AddComplexComponent( (BaseAddon) this, 11185, 1, 0, 5, 1033, -1, "Easter Basket", 1);// 15
			AddComplexComponent( (BaseAddon) this, 11185, -1, 0, 5, 1033, -1, "Easter Basket", 1);// 16
			AddComplexComponent( (BaseAddon) this, 892, 1, 1, 6, 1037, -1, "Easter Basket", 1);// 17
			AddComplexComponent( (BaseAddon) this, 892, 2, 1, 6, 1037, -1, "Easter Basket", 1);// 18
			AddComplexComponent( (BaseAddon) this, 3892, 0, 0, 0, 1260, -1, "Easter Grass", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3892, 0, 1, 0, 1167, -1, "Easter Grass", 1);// 20
			AddComplexComponent( (BaseAddon) this, 3892, 1, 1, 0, 1260, -1, "Easter Grass", 1);// 21
			AddComplexComponent( (BaseAddon) this, 3892, 1, 0, 0, 1167, -1, "Easter Grass", 1);// 22
			AddComplexComponent( (BaseAddon) this, 16830, 1, 1, 1, 1166, -1, "Easter Egg", 1);// 23
			AddComplexComponent( (BaseAddon) this, 16830, -1, 1, 1, 1161, -1, "Easter Egg", 1);// 24
			AddComplexComponent( (BaseAddon) this, 9762, 0, 1, 2, 1854, -1, "Chocolate Easter Bunny", 1);// 25

		}

		public EasterBasketLargeGiftAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class EasterBasketLargeGiftAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new EasterBasketLargeGiftAddon();
			}
		}

		[Constructable]
		public EasterBasketLargeGiftAddonDeed()
		{
			Name = "EasterBasketLargeGift";
		}

		public EasterBasketLargeGiftAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}
