
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BaseballFieldAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2123, 14, 14, 0}, {2123, 13, 14, 0}, {2123, 12, 14, 0}// 1	2	3	
			, {2121, 14, 14, 0}, {2121, 14, 13, 0}, {2121, 14, 12, 0}// 4	5	6	
			, {2121, 14, 11, 0}, {2121, 14, 10, 0}, {2121, 14, 9, 0}// 7	8	9	
			, {2121, 14, 8, 0}, {2121, 14, 7, 0}, {2121, 14, 6, 0}// 10	11	12	
			, {2121, 14, 5, 0}, {2121, 14, 4, 0}, {2121, 14, 3, 0}// 13	14	15	
			, {2121, 14, 2, 0}, {2121, 14, 1, 0}, {2121, 14, 0, 0}// 16	17	18	
			, {2121, 14, -1, 0}, {2121, 14, -2, 0}, {2121, 14, -3, 0}// 19	20	21	
			, {2121, 14, -4, 0}, {2121, 14, -5, 0}, {2121, 14, -6, 0}// 22	23	24	
			, {2121, 14, -10, 0}, {2121, 14, -11, 0}, {2121, 14, -12, 0}// 25	26	27	
			, {2121, 14, -13, 0}, {2123, 14, -14, 0}, {2123, 13, -14, 0}// 28	29	30	
			, {2123, 12, -14, 0}, {2123, 11, 14, 0}, {2123, 10, 14, 0}// 31	32	33	
			, {2123, 9, 14, 0}, {2123, 8, 14, 0}, {2123, 7, 14, 0}// 34	35	36	
			, {2123, 6, 14, 0}, {2123, 5, 14, 0}, {2123, 4, 14, 0}// 37	38	39	
			, {2123, 3, 14, 0}, {2123, 2, 14, 0}, {2123, 1, 14, 0}// 40	41	42	
			, {2123, 0, 14, 0}, {2123, -1, 14, 0}, {2123, -2, 14, 0}// 43	44	45	
			, {2123, -3, 14, 0}, {2123, -4, 14, 0}, {9272, -1, -1, 0}// 46	47	48	
			, {9256, -4, 9, 0}, {9253, -4, 7, 0}, {9255, 7, 7, 0}// 49	50	51	
			, {9254, 7, 9, 0}, {9254, 7, -4, 0}, {9256, 9, 9, 0}// 52	53	54	
			, {9256, 9, -4, 0}, {9253, 9, 7, 0}, {9270, 9, 8, 0}// 55	56	57	
			, {9271, 8, 9, 0}, {9271, 6, 8, 0}, {9271, 5, 8, 0}// 58	59	60	
			, {9271, 4, 8, 0}, {9271, 3, 8, 0}, {9271, 2, 8, 0}// 61	62	63	
			, {9271, 1, 8, 0}, {9271, 0, 8, 0}, {9271, -1, 8, 0}// 64	65	66	
			, {9271, -2, 8, 0}, {9271, -3, 8, 0}, {9270, 8, 6, 0}// 67	68	69	
			, {9270, 8, 5, 0}, {9270, 8, 4, 0}, {9270, 8, 3, 0}// 70	71	72	
			, {9270, 8, 2, 0}, {9270, 8, 1, 0}, {9270, 8, 0, 0}// 73	74	75	
			, {9270, 8, -1, 0}, {9270, 8, -2, 0}, {9270, 8, -3, 0}// 76	77	78	
			, {9267, 8, -4, 0}, {9265, 8, 7, 0}, {9268, 7, 8, 0}// 79	80	81	
			, {9266, -4, 8, 0}, {9256, -4, -4, 0}, {9255, 7, -6, 0}// 82	83	84	
			, {9253, 9, -6, 0}, {9270, 9, -5, 0}, {9271, 8, -6, 0}// 85	86	87	
			, {9253, -4, -6, 0}, {9268, 7, -5, 0}, {9271, 6, -5, 0}// 88	89	90	
			, {9271, 5, -5, 0}, {9271, 4, -5, 0}, {9271, 3, -5, 0}// 91	92	93	
			, {9271, 2, -5, 0}, {9271, 1, -5, 0}, {9271, 0, -5, 0}// 94	95	96	
			, {9271, -1, -5, 0}, {9271, -2, -5, 0}, {9271, -3, -5, 0}// 97	98	99	
			, {9266, -4, -5, 0}, {2861, 3, -7, 0}, {2123, -4, -8, 13}// 100	101	102	
			, {2123, 11, -14, 0}, {2123, 10, -14, 0}, {2123, 9, -14, 0}// 103	104	105	
			, {2123, 8, -14, 0}, {2123, 7, -14, 0}, {2123, 6, -14, 0}// 106	107	108	
			, {2123, 5, -14, 0}, {2123, 4, -14, 0}, {2123, 3, -14, 0}// 109	110	111	
			, {2123, 2, -14, 0}, {2123, 1, -14, 0}, {2123, 0, -14, 0}// 112	113	114	
			, {2123, -1, -14, 0}, {2123, -2, -14, 0}, {2123, -3, -14, 0}// 115	116	117	
			, {2121, -4, -13, 0}, {2121, -4, -11, 0}, {2121, -4, -12, 0}// 118	119	120	
			, {2121, -4, -12, 0}, {2121, -4, -10, 0}, {2121, -4, -9, 0}// 121	122	123	
			, {2121, -4, -8, 0}, {2123, -4, -8, 0}, {1848, -3, -13, 0}// 124	125	127	
			, {1848, -2, -13, 0}, {1848, -1, -13, 0}, {1848, 0, -13, 0}// 129	131	133	
			, {1848, 2, -13, 0}, {1848, 1, -13, 0}, {1848, 3, -13, 0}// 135	137	139	
			, {1848, 5, -13, 0}, {1848, -3, -12, 0}, {1848, -2, -12, 0}// 142	146	148	
			, {1848, 0, -12, 0}, {1848, -1, -12, 0}, {1848, 1, -12, 0}// 151	152	154	
			, {1848, 2, -12, 0}, {1848, 3, -12, 0}, {1848, 4, -12, 0}// 156	158	160	
			, {1848, 5, -12, 0}, {1848, 5, -12, 0}, {1848, 4, -13, 0}// 162	164	165	
			, {2861, 6, -10, 0}, {2861, 6, -13, 11}, {2861, 6, -12, 8}// 177	178	179	
			, {2861, 6, -11, 5}, {2861, 5, -11, 5}, {2861, 4, -11, 5}// 180	181	182	
			, {2861, 3, -11, 5}, {2861, 2, -11, 5}, {2861, 1, -11, 5}// 183	184	185	
			, {2861, 0, -11, 5}, {2861, -1, -11, 5}, {2861, -2, -11, 5}// 186	187	188	
			, {2861, -3, -11, 5}, {2861, -3, -12, 8}, {2861, -2, -12, 8}// 189	190	191	
			, {2861, -1, -12, 8}, {2861, 0, -12, 8}, {2861, 1, -12, 8}// 192	193	194	
			, {2861, 2, -12, 8}, {2861, 3, -12, 8}, {2861, 4, -12, 8}// 195	196	197	
			, {2861, 5, -12, 8}, {2861, 5, -13, 11}, {2861, 4, -13, 11}// 198	199	200	
			, {2861, 3, -13, 11}, {2861, 2, -13, 11}, {2861, 1, -13, 11}// 201	202	203	
			, {2861, 0, -13, 11}, {2861, -1, -13, 11}, {2861, -2, -13, 11}// 204	205	206	
			, {2861, -3, -13, 11}, {2861, 5, -10, 0}, {2861, 4, -10, 0}// 207	208	209	
			, {2861, 3, -10, 0}, {2861, 2, -10, 0}, {2861, 0, -10, 0}// 210	211	212	
			, {2861, 1, -10, 0}, {2861, -1, -10, 0}, {2861, -2, -10, 0}// 213	214	215	
			, {2861, -3, -10, 0}, {2861, 2, -7, 0}, {2861, 1, -7, 0}// 216	217	218	
			, {2861, 0, -7, 0}, {2861, -1, -7, 0}, {2121, -14, 14, 0}// 219	220	221	
			, {2123, -5, 14, 0}, {2123, -6, 14, 0}, {2123, -7, 14, 0}// 222	223	224	
			, {2123, -11, 14, 0}, {2123, -12, 14, 0}, {2123, -13, 14, 0}// 225	226	227	
			, {2121, -14, 13, 0}, {2121, -14, 12, 0}, {9255, -6, 7, 0}// 228	229	230	
			, {9254, -6, 9, 0}, {9270, -6, 8, 0}, {9271, -5, 9, 0}// 231	232	233	
			, {9254, -6, -4, 0}, {9265, -5, 7, 0}, {9270, -5, 6, 0}// 234	235	236	
			, {9270, -5, 5, 0}, {9270, -5, 4, 0}, {9270, -5, 3, 0}// 237	238	239	
			, {9270, -5, 2, 0}, {9270, -5, 1, 0}, {9270, -5, 0, 0}// 240	241	242	
			, {9270, -5, -1, 0}, {9270, -5, -2, 0}, {9270, -5, -3, 0}// 243	244	245	
			, {9267, -5, -4, 0}, {2860, -7, 3, 0}, {2121, -8, -4, 13}// 246	247	248	
			, {2121, -14, 11, 0}, {2121, -14, 10, 0}, {2121, -14, 9, 0}// 249	250	251	
			, {2121, -14, 8, 0}, {2121, -14, 7, 0}, {2121, -14, 6, 0}// 252	253	254	
			, {2121, -14, 5, 0}, {2121, -14, 4, 0}, {2121, -14, 3, 0}// 255	256	257	
			, {2121, -14, 2, 0}, {2121, -14, 1, 0}, {2121, -14, -1, 0}// 258	259	260	
			, {2121, -14, 0, 0}, {2121, -14, -2, 0}, {2121, -14, -3, 0}// 261	262	263	
			, {2121, -14, -3, 0}, {2102, -13, -4, 0}, {2102, -12, -4, 0}// 264	265	266	
			, {2102, -11, -4, 0}, {2102, -9, -4, 0}, {2102, -10, -4, 0}// 267	268	269	
			, {2102, -10, -4, 0}, {2102, -8, -4, 0}, {2121, -8, -4, 0}// 270	271	272	
			, {2860, -13, -3, 11}, {2860, -13, -2, 11}, {2860, -13, -1, 11}// 273	274	275	
			, {2860, -13, 0, 11}, {2860, -13, 1, 11}, {2860, -13, 2, 11}// 276	277	278	
			, {2860, -13, 3, 11}, {2860, -13, 4, 11}, {2860, -13, 5, 11}// 279	280	281	
			, {2860, -12, -3, 8}, {2860, -12, -2, 8}, {2860, -12, -1, 8}// 282	283	284	
			, {2860, -12, 0, 8}, {2860, -12, 1, 8}, {2860, -12, 2, 8}// 285	286	287	
			, {2860, -12, 3, 8}, {2860, -12, 4, 8}, {2860, -12, 5, 8}// 288	289	290	
			, {2860, -11, -3, 5}, {2860, -11, -2, 5}, {2860, -11, -1, 5}// 291	292	293	
			, {2860, -11, 0, 5}, {2860, -11, 1, 5}, {2860, -11, 2, 5}// 294	295	296	
			, {2860, -11, 4, 5}, {2860, -11, 3, 5}, {2860, -11, 5, 5}// 297	298	299	
			, {1848, -13, 4, 0}, {1848, -13, 4, 0}, {1848, -13, 3, 0}// 304	305	307	
			, {1848, -13, 3, 0}, {1848, -13, 2, 0}, {1848, -13, 2, 0}// 308	310	311	
			, {1848, -13, 1, 0}, {1848, -13, 1, 0}, {1848, -13, 0, 0}// 313	314	316	
			, {1848, -13, 0, 0}, {1848, -13, -1, 0}, {1848, -13, -1, 0}// 317	319	320	
			, {1848, -13, -2, 0}, {1848, -13, -2, 0}, {1848, -13, -3, 0}// 322	323	325	
			, {1848, -13, -3, 0}, {1848, -12, 3, 0}, {1848, -12, 3, 0}// 326	330	339	
			, {1848, -12, 2, 0}, {1848, -12, 1, 0}, {1848, -12, 0, 0}// 340	341	342	
			, {1848, -12, -1, 0}, {1848, -12, -2, 0}, {1848, -12, -3, 0}// 343	344	345	
			, {2860, -10, 5, 0}, {2860, -10, 4, 0}, {2860, -10, 3, 0}// 355	356	357	
			, {2860, -10, 2, 0}, {2860, -10, 1, 0}, {2860, -10, 0, 0}// 358	359	360	
			, {2860, -10, -1, 0}, {2860, -10, -2, 0}, {2860, -10, -3, 0}// 361	362	363	
			, {2860, -7, 2, 0}, {2860, -7, -1, 0}, {2860, -7, 0, 0}// 364	365	366	
			, {2860, -7, 1, 0}, {9271, -5, -6, 0}, {9270, -6, -5, 0}// 367	368	369	
			, {9255, -6, -6, 0}, {2123, -5, -8, 12}, {2123, -6, -8, 12}// 370	371	372	
			, {2123, -7, -8, 12}, {2121, -8, -5, 13}, {2121, -8, -6, 13}// 373	374	375	
			, {2121, -8, -7, 13}, {2121, -8, -5, 0}, {2121, -8, -6, 0}// 376	377	378	
			, {2121, -8, -7, 0}, {2123, -7, -8, 0}, {2123, -5, -8, 0}// 379	380	381	
			, {2123, -6, -8, 0}// 382	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BaseballFieldAddonDeed();
			}
		}

		[ Constructable ]
		public BaseballFieldAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1848, -3, -13, 6, 951, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1848, -2, -13, 6, 951, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1848, -1, -13, 6, 951, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1848, 0, -13, 6, 951, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1848, 2, -13, 6, 951, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1848, 1, -13, 6, 951, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1848, 3, -13, 6, 951, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1848, 4, -13, 6, 951, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1848, 5, -13, 6, 951, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1848, 6, -13, 6, 951, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1848, 6, -13, 1, 951, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1848, -3, -12, 3, 951, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1848, -2, -12, 3, 951, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1848, -1, -12, 3, 951, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1848, 0, -12, 3, 951, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1848, 1, -12, 3, 951, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1848, 2, -12, 3, 951, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1848, 3, -12, 3, 951, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1848, 4, -12, 3, 951, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1848, 5, -12, 3, 951, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1848, 6, -12, 3, 951, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1848, 6, -12, 0, 951, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1848, 6, -11, 0, 951, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1848, 5, -11, 0, 951, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1848, 4, -11, 0, 951, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1848, 3, -11, 0, 951, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1848, 2, -11, 0, 951, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1848, 1, -11, 0, 951, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1848, 0, -11, 0, 951, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1848, -1, -11, 0, 951, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1848, -2, -11, 0, 951, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1848, -3, -11, 0, 951, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1848, -13, 5, 6, 951, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1848, -13, 5, 0, 951, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1848, -13, 5, 0, 951, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1848, -13, 4, 6, 951, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1848, -13, 3, 6, 951, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1848, -13, 2, 6, 951, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1848, -13, 1, 6, 951, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1848, -13, 0, 6, 951, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1848, -13, -1, 6, 951, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 1848, -13, -2, 6, 951, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1848, -13, -3, 6, 951, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1848, -12, 5, 3, 951, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1848, -12, 5, 0, 951, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1848, -12, 3, 3, 951, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1848, -12, 2, 3, 951, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1848, -12, 1, 3, 951, -1, "", 1);// 332
			AddComplexComponent( (BaseAddon) this, 1848, -12, 0, 3, 951, -1, "", 1);// 333
			AddComplexComponent( (BaseAddon) this, 1848, -12, -1, 3, 951, -1, "", 1);// 334
			AddComplexComponent( (BaseAddon) this, 1848, -12, -2, 3, 951, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 1848, -12, -3, 3, 951, -1, "", 1);// 336
			AddComplexComponent( (BaseAddon) this, 1848, -12, 5, 0, 951, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 1848, -12, 4, 3, 951, -1, "", 1);// 338
			AddComplexComponent( (BaseAddon) this, 1848, -11, 5, 0, 951, -1, "", 1);// 346
			AddComplexComponent( (BaseAddon) this, 1848, -11, 4, 0, 951, -1, "", 1);// 347
			AddComplexComponent( (BaseAddon) this, 1848, -11, 3, 0, 951, -1, "", 1);// 348
			AddComplexComponent( (BaseAddon) this, 1848, -11, 2, 0, 951, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 1848, -11, 1, 0, 951, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 1848, -11, 0, 0, 951, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 1848, -11, -1, 0, 951, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 1848, -11, -2, 0, 951, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 1848, -11, -3, 0, 951, -1, "", 1);// 354

		}

		public BaseballFieldAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BaseballFieldAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BaseballFieldAddon();
			}
		}

		[Constructable]
		public BaseballFieldAddonDeed()
		{
			Name = "BaseballField";
		}

		public BaseballFieldAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}